
image: mcr.microsoft.com/dotnet/sdk:latest

include:
  - project: 'servidores/devops'
    file: '/pipes/backupzip.yml'
    ref: dev

stages:
  - build
  - deploy

# ### Define variables
#
variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/'
  BUILD_FOLDER: 'build'
  PROYECT_FOLDER_NAME: 'OndPayment'
  BUILD_PROJECT: '.\OndissPayment.API\OndissPayment.API.csproj'
  DEPLOY_FOLDER: $server\$env\$PROYECT_FOLDER_NAME
 
build:
  stage: build
  variables:
    SERVER_DEV: $server\dev
  script:
    - echo "servidor:$server env:$env serverdev:$SERVER_DEV"
    - echo $DEPLOY_FOLDER
    - dotnet restore $BUILD_PROJECT
    - dotnet build $BUILD_PROJECT 
    - dotnet publish -c Release -r win-x64 /p:EnvironmentName=Development $BUILD_PROJECT --output $BUILD_FOLDER
  rules:
    - if: $env != "" 
  artifacts:
    paths:
    - $BUILD_FOLDER
 
deploy:dev:
  extends: .deploy_and_backup_template
  stage: deploy
  needs: ["build"]
  variables:
    DEPLOY_FOLDER: '$server\$CI_COMMIT_REF_SLUG\$PROYECT_FOLDER_NAME' 
    SETTINGFILE: '$DEPLOY_FOLDER\appsettings.Development.json'
    BACKUP_FOLDER: '$DEPLOY_FOLDER'
  rules:
    - if: $CI_COMMIT_REF_SLUG == "dev"

deploy:test:
  extends: .deploy_and_backup_template
  stage: deploy
  needs: ["build"]
  variables:
    DEPLOY_FOLDER: '$server\$CI_COMMIT_REF_SLUG\$PROYECT_FOLDER_NAME'
    SETTINGFILE: '$DEPLOY_FOLDER\appsettings.Test.json'
    BACKUP_FOLDER: '$DEPLOY_FOLDER'
  rules:
    - if: $CI_COMMIT_REF_SLUG == "test"


deploy:prod:
  extends: .deploy_and_backup_template
  stage: deploy
  needs: ["build"]
  variables:
    DEPLOY_FOLDER: '\\payweb-1-prod\d$\$DEPLOYPROD\$PROYECT_FOLDER_NAME' 
    SETTINGFILE: '$DEPLOY_FOLDER\appsettings.Prod.json'
    BACKUP_FOLDER: '$DEPLOY_FOLDER'
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
  when: manual